name: Test & Publish Pact Contracts

on:
  push:
    branches: [ main ]

jobs:
  test-and-publish:
    runs-on: ubuntu-latest
    name: Run Consumer Pact Tests and Publish to PactFlow

    env:
      PACT_BROKER_BASE_URL: ${{ secrets.PACT_BROKER_BASE_URL }}
      PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}
      CONSUMER_VERSION: ${{ github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Restore dependencies
        run: dotnet restore PactSample.sln

      - name: Run Pact tests (generate contracts)
        run: dotnet test PactSample.Shipping.PactTests/PactSample.Shipping.PactTests.csproj --no-build

      - name: Publish Pact contracts to PactFlow
        uses: pactflow/actions/publish-pact-files@v2
        with:
          pactfiles: PactSample.Shipping.PactTests/pacts
          tag_with_git_branch: false
          broker_url: ${{ secrets.PACT_BROKER_BASE_URL }}
          token: ${{ secrets.PACT_BROKER_TOKEN }}
