name: Pact Verification

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      PACT_BROKER_URL: ${{ secrets.PACT_BROKER_BASE_URL }}
      PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}
      PACT_PROVIDER_VERSION: v${{ github.run_number }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore PactSample.sln

      - name: Run Pact Verification Tests
        run: dotnet test PactSample.Users.PactTests/PactSample.Users.PactTests.csproj
